---
label: Services
hide_body: false
display_field: title
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: true
    schema:
      format: markdown
  label: Description
- name: image
  type: file
  config:
    maxSize: '4'
  label: Image
pages:
- service-1.md
